version: "3.4"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    restart: always
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - ".env"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - local_postgres_data:/var/lib/postgresql/data/
      - local_postgres_data_backups:/backups

  prusaslicer-novnc:
    image: mikeah/prusaslicer-novnc
    container_name: prusaslicer-novnc
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=:0
      - VGL_DISPLAY=egl # needed to run without X server
      - SUPD_LOGLEVEL=INFO 
      - ENABLEHWGPU=true
      - VNC_RESOLUTION=1920x1080
      - NOVNC_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./prusaprints:/prints/
      - ./prusadata:/configs/
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: ./compose/server/Dockerfile
    restart: always
    command: /start
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - ".env"
    environment:
      - DB_HOST=postgres
    ports:
      - "8000:8000"
    user: ${DOCKER_UID}

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./compose/client/Dockerfile
    volumes:
      - ".:/app"
      # This line avoids copying local node_modules folder to the Docker container, and uses the ones installed during build
      - "/app/client/node_modules"
    ports:
      - "8080:8080"
      #- "49153:49153"
    environment:
      - CHOKIDAR_USEPOLLING=true
      
