# Generated by Django 3.2.6 on 2024-08-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adhesion_type',
            field=models.CharField(choices=[('skirt', 'Skirt'), ('brim', 'Brim'), ('raft', 'Raft'), ('none', 'None')], default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='infill_sparse_density',
            field=models.IntegerField(default=50, help_text='Infill percentage - used to calculate infill settings.'),
        ),
        migrations.AddField(
            model_name='user',
            name='support_structure',
            field=models.CharField(choices=[('normal', 'Normal'), ('tree', 'Tree')], default='normal', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='support_type',
            field=models.CharField(choices=[('buildplate', 'Buildplate'), ('everywhere', 'Everywhere')], default='everywhere', max_length=255),
        ),
    ]
