# Generated by Django 3.2.6 on 2024-08-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240808_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adhesion_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enable_support',
        ),
        migrations.RemoveField(
            model_name='user',
            name='infill_sparse_density',
        ),
        migrations.RemoveField(
            model_name='user',
            name='support_structure',
        ),
        migrations.RemoveField(
            model_name='user',
            name='support_type',
        ),
    ]
