# Generated by Django 3.2.6 on 2024-08-09 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuraSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('enable_support', models.BooleanField(default=False)),
                ('support_type', models.CharField(choices=[('buildplate', 'Buildplate'), ('everywhere', 'Everywhere')], default='everywhere', max_length=255)),
                ('support_structure', models.CharField(choices=[('normal', 'Normal'), ('tree', 'Tree')], default='normal', max_length=255)),
                ('infill_sparse_density', models.IntegerField(default=50, help_text='Infill percentage - used to calculate infill settings.')),
                ('adhesion_type', models.CharField(choices=[('skirt', 'Skirt'), ('brim', 'Brim'), ('raft', 'Raft'), ('none', 'None')], default='none', max_length=255)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
