# Generated by Django 3.2.6 on 2025-01-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curasettings',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Cura Settings'},
        ),
    ]
