# Generated by Django 3.2.6 on 2025-02-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cura', '0002_alter_curasettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='curasettings',
            name='initial_layer_height',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='curasettings',
            name='layer_height',
            field=models.FloatField(default=0.2),
        ),
    ]
