# Generated by Django 3.2.6 on 2024-07-17 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import limitless.utils.misc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to=limitless.utils.misc.datetime_appended_filepath)),
                ('print_config', models.FileField(blank=True, null=True, upload_to=limitless.utils.misc.datetime_appended_filepath)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
