# Generated by Django 3.2.6 on 2024-07-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-last_edited']},
        ),
    ]
