# Generated by Django 3.2.6 on 2024-07-29 17:15

from django.db import migrations, models
import django.db.models.deletion
import limitless.utils.misc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=limitless.utils.misc.datetime_appended_filepath)),
                ('file_type', models.CharField(blank=True, choices=[('MODEL', '3D Model (STL, etc.)'), ('IMAGE', 'Picture')], max_length=24, null=True)),
                ('print_config', models.FileField(blank=True, null=True, upload_to=limitless.utils.misc.datetime_appended_filepath)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
            options={
                'ordering': ['-last_edited'],
            },
        ),
    ]
