# Generated by Django 3.2.6 on 2024-07-29 17:15

from django.db import migrations


def move_files(apps, schema_editor):
    Project = apps.get_model("yourappname", "Project")
    ProjectFile = apps.get_model("yourappname", "ProjectFile")
    for project in Project.objects.exclude(model_3d__isnull=True).all():
        ProjectFile.objects.create(project=project, file=project.model_3d, print_config=project.print_config)


def reverse(apps, schema_editor):
    Project = apps.get_model("yourappname", "Project")
    ProjectFile = apps.get_model("yourappname", "ProjectFile")
    for project in Project.objects.all():
        project_model = project.files.filter(file_type=ProjectFile.TypeChoices.MODEL).first()
        if project_model:
            project.model_3d = project_model.file
            project.print_config = project_model.print_config
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectfile'),
    ]

    operations = [
        migrations.RunPython(move_files, reverse_code=reverse),
    ]
