# Generated by Django 3.2.6 on 2024-07-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20240729_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='model_3d',
        ),
        migrations.RemoveField(
            model_name='project',
            name='print_config',
        ),
    ]
