# Generated by Django 3.2.6 on 2024-08-07 17:17

from django.db import migrations, models
import limitless.utils.misc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20240805_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('cura_managed', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=limitless.utils.misc.datetime_appended_filepath)),
                ('config_tweaks', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_edited'],
            },
        ),
    ]
