# Generated by Django 3.2.6 on 2024-08-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_printer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['name']},
        ),
    ]
