# Generated by Django 3.2.6 on 2024-08-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cura', '0001_initial'),
        ('projects', '0009_alter_printer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='adhesion_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='enable_support',
        ),
        migrations.RemoveField(
            model_name='project',
            name='infill_sparse_density',
        ),
        migrations.RemoveField(
            model_name='project',
            name='support_structure',
        ),
        migrations.RemoveField(
            model_name='project',
            name='support_type',
        ),
        migrations.AddField(
            model_name='project',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='cura.curasettings'),
        ),
    ]
