# Generated by Django 3.2.6 on 2024-08-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cura', '0001_initial'),
        ('projects', '0010_auto_20240809_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='cura.curasettings'),
        ),
    ]
