# Generated by Django 3.2.6 on 2024-08-27 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cura', '0001_initial'),
        ('projects', '0011_alter_project_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='cura.curasettings'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('printer_settings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='cura.curasettings')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_edited'],
            },
        ),
    ]
