# Generated by Django 3.2.6 on 2024-08-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20240827_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='printer_settings',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='minimize_supports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='projects.printer'),
        ),
    ]
