# Generated by Django 3.2.6 on 2024-10-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recently_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
