# Generated by Django 3.2.6 on 2024-10-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_filament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filament',
            name='slug',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='filament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='projects.filament'),
        ),
    ]
